version: "3"
services:
  frontend:
    image: fintech-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: "frontend-app"
    volumes:
      - ./frontend/src:/app/src # for watching files
    ports:
      - "4200:4200"
  backend:
    image: fintech-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "backend-app"
    volumes:
        - ./backend:/app # for watching files
    ports:
      - "5000:5000"
